### ISSUE TITLE
启动helm-wrapper报错

### ISSUE THREAD

**Issue by singeleaf** [opskumu/helm-wrapper#13]
启动命令：
./helm-wrapper --config helm-wrapper.config

错误信息：
F0924 17:30:30.478389   25285 main.go:83] error unmarshaling JSON: while decoding JSON: json: unknown field "serverInfo"

helm-wrapper.config文件内容：

```
uploadPath: /tmp/charts
helmRepos:
  - name: apphub
    url: https://apphub.aliyuncs.com
```

环境信息
本地安装v3.0.0-alpha.2版本，操作系统centos7
