### ISSUE TITLE
install接口支持上传文件的方式

### ISSUE THREAD

**Issue by donhac** [opskumu/helm-wrapper#4]
现在部署只支持从 chart 仓库的方式，是否可以考虑接口直接支持上传 chart 压缩包的方式部署

**Comment by opskumu** [comment]
> 现在部署只支持从 chart 仓库的方式，是否可以考虑接口直接支持上传 chart 压缩包的方式部署

我晚点评估看看怎么做

**Comment by opskumu** [comment]
功能已经实现，具体接口如下：

+ upload chart
    - `POST`
    - `/api/charts/upload`

| Params | Description |
| :- | :- |
| chart | chart 包，必须为 .tgz 文件 |

+ list local charts
    - `GET`
    - `/api/charts/upload`

默认存放路径是 `/tmp/charts`，你可以通过 config 配置：

```
uploadPath: /tmp/charts
helmRepos:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
```

安装的时候指定实际包名即可，如 xxx.tgz
