### ISSUE TITLE
documentation on --config

### ISSUE THREAD

**Issue by wibed** [opskumu/helm-wrapper#61]
it is unclear what exactly makes a valid config.

the example shows:
```yaml
uploadPath: /tmp/charts
helmRepos:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
```

can i install external repos or only repos configured inside `--config <file>`
are there other configuration options?

appreciate your help, this is awesome

**Comment by opskumu** [comment]
@wibed yes, you can just config helmRepos like:

```yaml
helmRepos:
  - name: <repoName>
    url: <repoURL>
```
